# Generated by Django 3.2.2 on 2021-12-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
