# Generated by Django 3.2.2 on 2021-12-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
