# Generated by Django 3.2.2 on 2022-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='ad1',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='ad2',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='currency',
            field=models.CharField(default=1111, help_text='e.g dollar', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='currency_shortcode',
            field=models.CharField(default=111, help_text='e.g usd', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='currency_symbol',
            field=models.CharField(default=1, help_text='e.g $', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='google_analytics',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
