# Generated by Django 3.2.2 on 2021-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=True),
        ),
    ]
