# Generated by Django 3.2.2 on 2022-07-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
