# Generated by Django 3.2.2 on 2021-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20211227_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
