# Generated by Django 3.2.2 on 2021-12-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_product_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('electronics', 'electronics'), ('accessories', 'accessories')], default='electronics', max_length=50),
        ),
    ]
