# Generated by Django 3.2.2 on 2022-01-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_auto_20211227_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment',
            field=models.CharField(default='apartment', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone1',
            field=models.IntegerField(default='08122799902'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
