# Generated by Django 3.2.2 on 2022-01-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20220101_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Nigeria', max_length=200),
            preserve_default=False,
        ),
    ]
