# Generated by Django 3.2.2 on 2022-07-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20220726_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
