# Generated by Django 3.2.2 on 2022-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20220710_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
