# Generated by Django 3.2.2 on 2022-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20220726_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.FloatField(),
        ),
    ]
