# Generated by Django 3.2.2 on 2022-07-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_auto_20220726_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
