# Generated by Django 3.2.2 on 2022-07-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_sent',
            new_name='date_received',
        ),
    ]
