# Generated by Django 3.2.2 on 2022-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_auto_20220728_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_uploaded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Products'),
        ),
    ]
