# Generated by Django 3.2.2 on 2022-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_auto_20220730_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.FloatField(default=0),
        ),
    ]
