# Generated by Django 3.2.2 on 2022-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_review',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
