# Generated by Django 3.2.2 on 2022-08-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_product_manufacturer_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_in_percentage',
            new_name='percentage_discount',
        ),
    ]
