# Generated by Django 3.2.2 on 2022-11-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_rename_discount_in_percentage_product_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Documents/Products'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_link',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=True, help_text='Means high in demand'),
        ),
    ]
